# Generated by Django 5.0.2 on 2024-03-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0002_cliente_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
    ]
