# Generated by Django 5.0.2 on 2024-03-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0005_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='venta',
        ),
    ]
