# Generated by Django 5.0.2 on 2024-03-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0008_remove_venta_equipos_remove_venta_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appventas.equipo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appventas.venta')),
            ],
        ),
    ]
