# Generated by Django 5.0.2 on 2024-03-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0009_venta_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
