# Generated by Django 5.0.2 on 2024-03-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0013_venta_detalleventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
