# Generated by Django 5.0.2 on 2024-03-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0014_delete_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appventas.equipo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appventas.venta')),
            ],
        ),
    ]
